// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package ensicoin_rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error int32

const (
	Error_INVALID_DATA Error = 0
)

var Error_name = map[int32]string{
	0: "INVALID_DATA",
}
var Error_value = map[string]int32{
	"INVALID_DATA": 0,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{0}
}

type Address struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Peer struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{1}
}
func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (dst *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(dst, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Outpoint struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outpoint) Reset()         { *m = Outpoint{} }
func (m *Outpoint) String() string { return proto.CompactTextString(m) }
func (*Outpoint) ProtoMessage()    {}
func (*Outpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{2}
}
func (m *Outpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outpoint.Unmarshal(m, b)
}
func (m *Outpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outpoint.Marshal(b, m, deterministic)
}
func (dst *Outpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outpoint.Merge(dst, src)
}
func (m *Outpoint) XXX_Size() int {
	return xxx_messageInfo_Outpoint.Size(m)
}
func (m *Outpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Outpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Outpoint proto.InternalMessageInfo

func (m *Outpoint) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Outpoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type TxInput struct {
	PreviousOutput       *Outpoint `protobuf:"bytes,1,opt,name=previous_output,json=previousOutput,proto3" json:"previous_output,omitempty"`
	Script               []byte    `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{3}
}
func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (dst *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(dst, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetPreviousOutput() *Outpoint {
	if m != nil {
		return m.PreviousOutput
	}
	return nil
}

func (m *TxInput) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type TxOutput struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{4}
}
func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (dst *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(dst, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOutput) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type Tx struct {
	Version              uint32      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string    `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	Inputs               []*TxInput  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TxOutput `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Hash                 []byte      `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{5}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Tx) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Tx) GetInputs() []*TxInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Tx) GetOutputs() []*TxOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Tx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Block struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	PrevBlock            []byte   `protobuf:"bytes,4,opt,name=prev_block,json=prevBlock,proto3" json:"prev_block,omitempty"`
	MerkleRoot           []byte   `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	Timestamp            uint64   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Target               []byte   `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,9,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{6}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Block) GetPrevBlock() []byte {
	if m != nil {
		return m.PrevBlock
	}
	return nil
}

func (m *Block) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *Block) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type BlockTemplate struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	PrevBlock            []byte   `protobuf:"bytes,3,opt,name=prev_block,json=prevBlock,proto3" json:"prev_block,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height               uint32   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Target               []byte   `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockTemplate) Reset()         { *m = BlockTemplate{} }
func (m *BlockTemplate) String() string { return proto.CompactTextString(m) }
func (*BlockTemplate) ProtoMessage()    {}
func (*BlockTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{7}
}
func (m *BlockTemplate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockTemplate.Unmarshal(m, b)
}
func (m *BlockTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockTemplate.Marshal(b, m, deterministic)
}
func (dst *BlockTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockTemplate.Merge(dst, src)
}
func (m *BlockTemplate) XXX_Size() int {
	return xxx_messageInfo_BlockTemplate.Size(m)
}
func (m *BlockTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_BlockTemplate proto.InternalMessageInfo

func (m *BlockTemplate) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockTemplate) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *BlockTemplate) GetPrevBlock() []byte {
	if m != nil {
		return m.PrevBlock
	}
	return nil
}

func (m *BlockTemplate) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockTemplate) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockTemplate) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

type Reply struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=ensicoin_rpc.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{8}
}
func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (dst *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(dst, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_INVALID_DATA
}

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{9}
}
func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(dst, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoReply struct {
	Implementation       string   `protobuf:"bytes,1,opt,name=implementation,proto3" json:"implementation,omitempty"`
	ProtocolVersion      uint32   `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	BestBlockHash        []byte   `protobuf:"bytes,3,opt,name=best_block_hash,json=bestBlockHash,proto3" json:"best_block_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoReply) Reset()         { *m = GetInfoReply{} }
func (m *GetInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetInfoReply) ProtoMessage()    {}
func (*GetInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{10}
}
func (m *GetInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoReply.Unmarshal(m, b)
}
func (m *GetInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoReply.Marshal(b, m, deterministic)
}
func (dst *GetInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoReply.Merge(dst, src)
}
func (m *GetInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetInfoReply.Size(m)
}
func (m *GetInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoReply proto.InternalMessageInfo

func (m *GetInfoReply) GetImplementation() string {
	if m != nil {
		return m.Implementation
	}
	return ""
}

func (m *GetInfoReply) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *GetInfoReply) GetBestBlockHash() []byte {
	if m != nil {
		return m.BestBlockHash
	}
	return nil
}

type PublishRawTxRequest struct {
	RawTx                []byte   `protobuf:"bytes,1,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRawTxRequest) Reset()         { *m = PublishRawTxRequest{} }
func (m *PublishRawTxRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRawTxRequest) ProtoMessage()    {}
func (*PublishRawTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{11}
}
func (m *PublishRawTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRawTxRequest.Unmarshal(m, b)
}
func (m *PublishRawTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRawTxRequest.Marshal(b, m, deterministic)
}
func (dst *PublishRawTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRawTxRequest.Merge(dst, src)
}
func (m *PublishRawTxRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRawTxRequest.Size(m)
}
func (m *PublishRawTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRawTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRawTxRequest proto.InternalMessageInfo

func (m *PublishRawTxRequest) GetRawTx() []byte {
	if m != nil {
		return m.RawTx
	}
	return nil
}

type PublishRawTxReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRawTxReply) Reset()         { *m = PublishRawTxReply{} }
func (m *PublishRawTxReply) String() string { return proto.CompactTextString(m) }
func (*PublishRawTxReply) ProtoMessage()    {}
func (*PublishRawTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{12}
}
func (m *PublishRawTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRawTxReply.Unmarshal(m, b)
}
func (m *PublishRawTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRawTxReply.Marshal(b, m, deterministic)
}
func (dst *PublishRawTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRawTxReply.Merge(dst, src)
}
func (m *PublishRawTxReply) XXX_Size() int {
	return xxx_messageInfo_PublishRawTxReply.Size(m)
}
func (m *PublishRawTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRawTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRawTxReply proto.InternalMessageInfo

type PublishRawBlockRequest struct {
	RawBlock             []byte   `protobuf:"bytes,1,opt,name=raw_block,json=rawBlock,proto3" json:"raw_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRawBlockRequest) Reset()         { *m = PublishRawBlockRequest{} }
func (m *PublishRawBlockRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRawBlockRequest) ProtoMessage()    {}
func (*PublishRawBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{13}
}
func (m *PublishRawBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRawBlockRequest.Unmarshal(m, b)
}
func (m *PublishRawBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRawBlockRequest.Marshal(b, m, deterministic)
}
func (dst *PublishRawBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRawBlockRequest.Merge(dst, src)
}
func (m *PublishRawBlockRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRawBlockRequest.Size(m)
}
func (m *PublishRawBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRawBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRawBlockRequest proto.InternalMessageInfo

func (m *PublishRawBlockRequest) GetRawBlock() []byte {
	if m != nil {
		return m.RawBlock
	}
	return nil
}

type PublishRawBlockReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRawBlockReply) Reset()         { *m = PublishRawBlockReply{} }
func (m *PublishRawBlockReply) String() string { return proto.CompactTextString(m) }
func (*PublishRawBlockReply) ProtoMessage()    {}
func (*PublishRawBlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{14}
}
func (m *PublishRawBlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRawBlockReply.Unmarshal(m, b)
}
func (m *PublishRawBlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRawBlockReply.Marshal(b, m, deterministic)
}
func (dst *PublishRawBlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRawBlockReply.Merge(dst, src)
}
func (m *PublishRawBlockReply) XXX_Size() int {
	return xxx_messageInfo_PublishRawBlockReply.Size(m)
}
func (m *PublishRawBlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRawBlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRawBlockReply proto.InternalMessageInfo

type GetBlockTemplateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockTemplateRequest) Reset()         { *m = GetBlockTemplateRequest{} }
func (m *GetBlockTemplateRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockTemplateRequest) ProtoMessage()    {}
func (*GetBlockTemplateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{15}
}
func (m *GetBlockTemplateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTemplateRequest.Unmarshal(m, b)
}
func (m *GetBlockTemplateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTemplateRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockTemplateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTemplateRequest.Merge(dst, src)
}
func (m *GetBlockTemplateRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockTemplateRequest.Size(m)
}
func (m *GetBlockTemplateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTemplateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTemplateRequest proto.InternalMessageInfo

type GetBlockTemplateReply struct {
	BlockTemplate        *BlockTemplate `protobuf:"bytes,1,opt,name=block_template,json=blockTemplate,proto3" json:"block_template,omitempty"`
	Txs                  []*Tx          `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBlockTemplateReply) Reset()         { *m = GetBlockTemplateReply{} }
func (m *GetBlockTemplateReply) String() string { return proto.CompactTextString(m) }
func (*GetBlockTemplateReply) ProtoMessage()    {}
func (*GetBlockTemplateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{16}
}
func (m *GetBlockTemplateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockTemplateReply.Unmarshal(m, b)
}
func (m *GetBlockTemplateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockTemplateReply.Marshal(b, m, deterministic)
}
func (dst *GetBlockTemplateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockTemplateReply.Merge(dst, src)
}
func (m *GetBlockTemplateReply) XXX_Size() int {
	return xxx_messageInfo_GetBlockTemplateReply.Size(m)
}
func (m *GetBlockTemplateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockTemplateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockTemplateReply proto.InternalMessageInfo

func (m *GetBlockTemplateReply) GetBlockTemplate() *BlockTemplate {
	if m != nil {
		return m.BlockTemplate
	}
	return nil
}

func (m *GetBlockTemplateReply) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type GetBlockByHashRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashRequest) Reset()         { *m = GetBlockByHashRequest{} }
func (m *GetBlockByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashRequest) ProtoMessage()    {}
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{17}
}
func (m *GetBlockByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashRequest.Merge(dst, src)
}
func (m *GetBlockByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashRequest.Size(m)
}
func (m *GetBlockByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashRequest proto.InternalMessageInfo

func (m *GetBlockByHashRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetBlockByHashReply struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashReply) Reset()         { *m = GetBlockByHashReply{} }
func (m *GetBlockByHashReply) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashReply) ProtoMessage()    {}
func (*GetBlockByHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{18}
}
func (m *GetBlockByHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashReply.Unmarshal(m, b)
}
func (m *GetBlockByHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashReply.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashReply.Merge(dst, src)
}
func (m *GetBlockByHashReply) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashReply.Size(m)
}
func (m *GetBlockByHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashReply proto.InternalMessageInfo

func (m *GetBlockByHashReply) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetTxByHashRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxByHashRequest) Reset()         { *m = GetTxByHashRequest{} }
func (m *GetTxByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetTxByHashRequest) ProtoMessage()    {}
func (*GetTxByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{19}
}
func (m *GetTxByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxByHashRequest.Unmarshal(m, b)
}
func (m *GetTxByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetTxByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxByHashRequest.Merge(dst, src)
}
func (m *GetTxByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetTxByHashRequest.Size(m)
}
func (m *GetTxByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxByHashRequest proto.InternalMessageInfo

func (m *GetTxByHashRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetTxByHashReply struct {
	Tx                   *Tx      `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTxByHashReply) Reset()         { *m = GetTxByHashReply{} }
func (m *GetTxByHashReply) String() string { return proto.CompactTextString(m) }
func (*GetTxByHashReply) ProtoMessage()    {}
func (*GetTxByHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{20}
}
func (m *GetTxByHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTxByHashReply.Unmarshal(m, b)
}
func (m *GetTxByHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTxByHashReply.Marshal(b, m, deterministic)
}
func (dst *GetTxByHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTxByHashReply.Merge(dst, src)
}
func (m *GetTxByHashReply) XXX_Size() int {
	return xxx_messageInfo_GetTxByHashReply.Size(m)
}
func (m *GetTxByHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTxByHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTxByHashReply proto.InternalMessageInfo

func (m *GetTxByHashReply) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

type ConnectPeerRequest struct {
	Peer                 *Peer    `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectPeerRequest) Reset()         { *m = ConnectPeerRequest{} }
func (m *ConnectPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerRequest) ProtoMessage()    {}
func (*ConnectPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{21}
}
func (m *ConnectPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerRequest.Unmarshal(m, b)
}
func (m *ConnectPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerRequest.Merge(dst, src)
}
func (m *ConnectPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerRequest.Size(m)
}
func (m *ConnectPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerRequest proto.InternalMessageInfo

func (m *ConnectPeerRequest) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type ConnectPeerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectPeerReply) Reset()         { *m = ConnectPeerReply{} }
func (m *ConnectPeerReply) String() string { return proto.CompactTextString(m) }
func (*ConnectPeerReply) ProtoMessage()    {}
func (*ConnectPeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{22}
}
func (m *ConnectPeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectPeerReply.Unmarshal(m, b)
}
func (m *ConnectPeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectPeerReply.Marshal(b, m, deterministic)
}
func (dst *ConnectPeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectPeerReply.Merge(dst, src)
}
func (m *ConnectPeerReply) XXX_Size() int {
	return xxx_messageInfo_ConnectPeerReply.Size(m)
}
func (m *ConnectPeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectPeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectPeerReply proto.InternalMessageInfo

type DisconnectPeerRequest struct {
	Peer                 *Peer    `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectPeerRequest) Reset()         { *m = DisconnectPeerRequest{} }
func (m *DisconnectPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectPeerRequest) ProtoMessage()    {}
func (*DisconnectPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{23}
}
func (m *DisconnectPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectPeerRequest.Unmarshal(m, b)
}
func (m *DisconnectPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectPeerRequest.Marshal(b, m, deterministic)
}
func (dst *DisconnectPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectPeerRequest.Merge(dst, src)
}
func (m *DisconnectPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectPeerRequest.Size(m)
}
func (m *DisconnectPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectPeerRequest proto.InternalMessageInfo

func (m *DisconnectPeerRequest) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type DisconnectPeerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectPeerReply) Reset()         { *m = DisconnectPeerReply{} }
func (m *DisconnectPeerReply) String() string { return proto.CompactTextString(m) }
func (*DisconnectPeerReply) ProtoMessage()    {}
func (*DisconnectPeerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_f908e3307c671c02, []int{24}
}
func (m *DisconnectPeerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectPeerReply.Unmarshal(m, b)
}
func (m *DisconnectPeerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectPeerReply.Marshal(b, m, deterministic)
}
func (dst *DisconnectPeerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectPeerReply.Merge(dst, src)
}
func (m *DisconnectPeerReply) XXX_Size() int {
	return xxx_messageInfo_DisconnectPeerReply.Size(m)
}
func (m *DisconnectPeerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectPeerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectPeerReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Address)(nil), "ensicoin_rpc.Address")
	proto.RegisterType((*Peer)(nil), "ensicoin_rpc.Peer")
	proto.RegisterType((*Outpoint)(nil), "ensicoin_rpc.Outpoint")
	proto.RegisterType((*TxInput)(nil), "ensicoin_rpc.TxInput")
	proto.RegisterType((*TxOutput)(nil), "ensicoin_rpc.TxOutput")
	proto.RegisterType((*Tx)(nil), "ensicoin_rpc.Tx")
	proto.RegisterType((*Block)(nil), "ensicoin_rpc.Block")
	proto.RegisterType((*BlockTemplate)(nil), "ensicoin_rpc.BlockTemplate")
	proto.RegisterType((*Reply)(nil), "ensicoin_rpc.Reply")
	proto.RegisterType((*GetInfoRequest)(nil), "ensicoin_rpc.GetInfoRequest")
	proto.RegisterType((*GetInfoReply)(nil), "ensicoin_rpc.GetInfoReply")
	proto.RegisterType((*PublishRawTxRequest)(nil), "ensicoin_rpc.PublishRawTxRequest")
	proto.RegisterType((*PublishRawTxReply)(nil), "ensicoin_rpc.PublishRawTxReply")
	proto.RegisterType((*PublishRawBlockRequest)(nil), "ensicoin_rpc.PublishRawBlockRequest")
	proto.RegisterType((*PublishRawBlockReply)(nil), "ensicoin_rpc.PublishRawBlockReply")
	proto.RegisterType((*GetBlockTemplateRequest)(nil), "ensicoin_rpc.GetBlockTemplateRequest")
	proto.RegisterType((*GetBlockTemplateReply)(nil), "ensicoin_rpc.GetBlockTemplateReply")
	proto.RegisterType((*GetBlockByHashRequest)(nil), "ensicoin_rpc.GetBlockByHashRequest")
	proto.RegisterType((*GetBlockByHashReply)(nil), "ensicoin_rpc.GetBlockByHashReply")
	proto.RegisterType((*GetTxByHashRequest)(nil), "ensicoin_rpc.GetTxByHashRequest")
	proto.RegisterType((*GetTxByHashReply)(nil), "ensicoin_rpc.GetTxByHashReply")
	proto.RegisterType((*ConnectPeerRequest)(nil), "ensicoin_rpc.ConnectPeerRequest")
	proto.RegisterType((*ConnectPeerReply)(nil), "ensicoin_rpc.ConnectPeerReply")
	proto.RegisterType((*DisconnectPeerRequest)(nil), "ensicoin_rpc.DisconnectPeerRequest")
	proto.RegisterType((*DisconnectPeerReply)(nil), "ensicoin_rpc.DisconnectPeerReply")
	proto.RegisterEnum("ensicoin_rpc.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoReply, error)
	PublishRawTx(ctx context.Context, in *PublishRawTxRequest, opts ...grpc.CallOption) (*PublishRawTxReply, error)
	PublishRawBlock(ctx context.Context, in *PublishRawBlockRequest, opts ...grpc.CallOption) (*PublishRawBlockReply, error)
	GetBlockTemplate(ctx context.Context, in *GetBlockTemplateRequest, opts ...grpc.CallOption) (Node_GetBlockTemplateClient, error)
	GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashReply, error)
	GetTxByHash(ctx context.Context, in *GetTxByHashRequest, opts ...grpc.CallOption) (*GetTxByHashReply, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerReply, error)
	DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerReply, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoReply, error) {
	out := new(GetInfoReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PublishRawTx(ctx context.Context, in *PublishRawTxRequest, opts ...grpc.CallOption) (*PublishRawTxReply, error) {
	out := new(PublishRawTxReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/PublishRawTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) PublishRawBlock(ctx context.Context, in *PublishRawBlockRequest, opts ...grpc.CallOption) (*PublishRawBlockReply, error) {
	out := new(PublishRawBlockReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/PublishRawBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetBlockTemplate(ctx context.Context, in *GetBlockTemplateRequest, opts ...grpc.CallOption) (Node_GetBlockTemplateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Node_serviceDesc.Streams[0], "/ensicoin_rpc.Node/GetBlockTemplate", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeGetBlockTemplateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Node_GetBlockTemplateClient interface {
	Recv() (*GetBlockTemplateReply, error)
	grpc.ClientStream
}

type nodeGetBlockTemplateClient struct {
	grpc.ClientStream
}

func (x *nodeGetBlockTemplateClient) Recv() (*GetBlockTemplateReply, error) {
	m := new(GetBlockTemplateReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeClient) GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashReply, error) {
	out := new(GetBlockByHashReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) GetTxByHash(ctx context.Context, in *GetTxByHashRequest, opts ...grpc.CallOption) (*GetTxByHashReply, error) {
	out := new(GetTxByHashReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/GetTxByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerReply, error) {
	out := new(ConnectPeerReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/ConnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerReply, error) {
	out := new(DisconnectPeerReply)
	err := c.cc.Invoke(ctx, "/ensicoin_rpc.Node/DisconnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoReply, error)
	PublishRawTx(context.Context, *PublishRawTxRequest) (*PublishRawTxReply, error)
	PublishRawBlock(context.Context, *PublishRawBlockRequest) (*PublishRawBlockReply, error)
	GetBlockTemplate(*GetBlockTemplateRequest, Node_GetBlockTemplateServer) error
	GetBlockByHash(context.Context, *GetBlockByHashRequest) (*GetBlockByHashReply, error)
	GetTxByHash(context.Context, *GetTxByHashRequest) (*GetTxByHashReply, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerReply, error)
	DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerReply, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PublishRawTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRawTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PublishRawTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/PublishRawTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PublishRawTx(ctx, req.(*PublishRawTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_PublishRawBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRawBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).PublishRawBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/PublishRawBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).PublishRawBlock(ctx, req.(*PublishRawBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetBlockTemplate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlockTemplateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServer).GetBlockTemplate(m, &nodeGetBlockTemplateServer{stream})
}

type Node_GetBlockTemplateServer interface {
	Send(*GetBlockTemplateReply) error
	grpc.ServerStream
}

type nodeGetBlockTemplateServer struct {
	grpc.ServerStream
}

func (x *nodeGetBlockTemplateServer) Send(m *GetBlockTemplateReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Node_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetBlockByHash(ctx, req.(*GetBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_GetTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).GetTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/GetTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).GetTxByHash(ctx, req.(*GetTxByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_DisconnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).DisconnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ensicoin_rpc.Node/DisconnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).DisconnectPeer(ctx, req.(*DisconnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ensicoin_rpc.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Node_GetInfo_Handler,
		},
		{
			MethodName: "PublishRawTx",
			Handler:    _Node_PublishRawTx_Handler,
		},
		{
			MethodName: "PublishRawBlock",
			Handler:    _Node_PublishRawBlock_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _Node_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetTxByHash",
			Handler:    _Node_GetTxByHash_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _Node_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectPeer",
			Handler:    _Node_DisconnectPeer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlockTemplate",
			Handler:       _Node_GetBlockTemplate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node.proto",
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_node_f908e3307c671c02) }

var fileDescriptor_node_f908e3307c671c02 = []byte{
	// 939 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x6f, 0x1b, 0x45,
	0x14, 0x8d, 0xd7, 0x5e, 0x3b, 0xbe, 0xb1, 0x1d, 0x33, 0x8e, 0xcd, 0xd6, 0x2d, 0xd4, 0x1d, 0x20,
	0x4a, 0x81, 0x86, 0x2a, 0x14, 0xc1, 0x03, 0x52, 0x49, 0x48, 0x15, 0x22, 0xa1, 0xb6, 0x8c, 0xac,
	0x3e, 0x20, 0x21, 0x6b, 0x6d, 0x4f, 0xe3, 0x55, 0xd7, 0x3b, 0xcb, 0xec, 0x38, 0xd9, 0x3c, 0xf1,
	0xcc, 0x4f, 0x41, 0xe2, 0x67, 0xf0, 0xb7, 0x90, 0xd0, 0x7c, 0x6c, 0xbc, 0xb3, 0xb6, 0x13, 0xd1,
	0x37, 0xcf, 0x9d, 0x73, 0xcf, 0xdc, 0x73, 0xe6, 0xcc, 0x1a, 0x20, 0x62, 0x53, 0x7a, 0x18, 0x73,
	0x26, 0x18, 0x6a, 0xd0, 0x28, 0x09, 0x26, 0x2c, 0x88, 0x46, 0x3c, 0x9e, 0xe0, 0x27, 0x50, 0x3b,
	0x9e, 0x4e, 0x39, 0x4d, 0x12, 0xd4, 0x02, 0x27, 0x88, 0xbd, 0xd2, 0xa0, 0x74, 0x50, 0x27, 0x4e,
	0x10, 0x23, 0x04, 0x95, 0x98, 0x71, 0xe1, 0x39, 0x83, 0xd2, 0x41, 0x93, 0xa8, 0xdf, 0xf8, 0x5b,
	0xa8, 0xbc, 0xa6, 0x94, 0xa3, 0xaf, 0xa0, 0xe6, 0xeb, 0x36, 0xd5, 0xb0, 0x73, 0xd4, 0x3d, 0xcc,
	0xd3, 0x1e, 0x1a, 0x4e, 0x92, 0xa1, 0xf0, 0x33, 0xd8, 0x7e, 0xb5, 0x10, 0x31, 0x0b, 0x22, 0x21,
	0x89, 0x67, 0x7e, 0x32, 0x53, 0x9d, 0x0d, 0xa2, 0x7e, 0xa3, 0x3d, 0x70, 0x83, 0x68, 0x4a, 0x53,
	0x73, 0x9a, 0x5e, 0xe0, 0x31, 0xd4, 0x86, 0xe9, 0x79, 0x14, 0x2f, 0x04, 0x7a, 0x0e, 0xbb, 0x31,
	0xa7, 0x97, 0x01, 0x5b, 0x24, 0x23, 0xb6, 0x10, 0xf1, 0x42, 0x98, 0x93, 0x7b, 0xf6, 0xc9, 0xd9,
	0x29, 0xa4, 0x95, 0xc1, 0x5f, 0x29, 0x34, 0xea, 0x41, 0x35, 0x99, 0xf0, 0x20, 0xd6, 0x82, 0x1a,
	0xc4, 0xac, 0xf0, 0x77, 0xb0, 0x3d, 0x4c, 0x0d, 0x66, 0x0f, 0xdc, 0x4b, 0x3f, 0x5c, 0x50, 0x45,
	0x5d, 0x21, 0x7a, 0xb1, 0xb1, 0xf3, 0xaf, 0x12, 0x38, 0xc3, 0x14, 0x79, 0x50, 0xbb, 0xa4, 0x3c,
	0x09, 0x58, 0xa4, 0xda, 0x9a, 0x24, 0x5b, 0x4a, 0xba, 0xb7, 0xa1, 0x7f, 0x91, 0x78, 0xce, 0xa0,
	0x7c, 0x50, 0x27, 0x7a, 0x81, 0x9e, 0x40, 0x35, 0x90, 0x92, 0x12, 0xaf, 0x3c, 0x28, 0xaf, 0x5a,
	0x67, 0x04, 0x13, 0x03, 0x42, 0x4f, 0xa1, 0xa6, 0xf5, 0x26, 0x5e, 0x45, 0xe1, 0x7b, 0x45, 0xbc,
	0x1e, 0x9e, 0x64, 0xb0, 0x1b, 0x7f, 0xdd, 0xa5, 0xbf, 0xf8, 0xdf, 0x12, 0xb8, 0x27, 0x21, 0x9b,
	0xbc, 0x5b, 0xeb, 0x7e, 0x4e, 0x82, 0xb3, 0x41, 0x42, 0x39, 0x2f, 0xe1, 0x23, 0x00, 0xe9, 0xee,
	0x68, 0x2c, 0x19, 0xbd, 0x8a, 0x62, 0xaa, 0xcb, 0x8a, 0x3e, 0xe2, 0x21, 0xec, 0xcc, 0x29, 0x7f,
	0x17, 0xd2, 0x11, 0x67, 0x4c, 0x98, 0x39, 0x40, 0x97, 0x08, 0x63, 0x02, 0x3d, 0x80, 0xba, 0x08,
	0xe6, 0x34, 0x11, 0xfe, 0x3c, 0xf6, 0xaa, 0xca, 0xeb, 0x65, 0x41, 0xfa, 0x3d, 0xa3, 0xc1, 0xc5,
	0x4c, 0x78, 0x35, 0x35, 0x8c, 0x59, 0xc9, 0xba, 0xf0, 0xf9, 0x05, 0x15, 0xde, 0xb6, 0xbe, 0x07,
	0xbd, 0x42, 0x18, 0xca, 0x22, 0x4d, 0xbc, 0xba, 0x72, 0xa7, 0x5d, 0x74, 0x87, 0xc8, 0x4d, 0xfc,
	0x77, 0x09, 0x9a, 0x6a, 0xb8, 0x21, 0x9d, 0xc7, 0xa1, 0x2f, 0xe8, 0xff, 0xbe, 0x36, 0x5b, 0x73,
	0xb9, 0xa8, 0xd9, 0x92, 0x54, 0xd9, 0x2c, 0xc9, 0xdd, 0x20, 0xa9, 0x9a, 0x97, 0x84, 0x8f, 0xc0,
	0x25, 0x34, 0x0e, 0xaf, 0xd1, 0x63, 0x70, 0x29, 0xe7, 0x8c, 0xab, 0x19, 0x5b, 0x47, 0x1d, 0x5b,
	0xdd, 0x0b, 0xb9, 0x45, 0x34, 0x02, 0xb7, 0xa1, 0x75, 0x46, 0xc5, 0x79, 0xf4, 0x96, 0x11, 0xfa,
	0xfb, 0x82, 0x26, 0x02, 0xff, 0x59, 0x82, 0xc6, 0x4d, 0x49, 0xb2, 0xed, 0x43, 0x2b, 0x98, 0xc7,
	0x21, 0x9d, 0xd3, 0x48, 0xf8, 0x22, 0x93, 0x5e, 0x27, 0x85, 0x2a, 0x7a, 0x0c, 0x6d, 0xf5, 0xb1,
	0x98, 0xb0, 0x70, 0x64, 0x07, 0x63, 0x37, 0xab, 0xbf, 0x31, 0x66, 0xed, 0xc3, 0xee, 0x98, 0x26,
	0x42, 0xdb, 0x32, 0x52, 0xc9, 0xd2, 0xde, 0x34, 0x65, 0x59, 0x79, 0xf3, 0x93, 0x0c, 0xe0, 0x97,
	0xd0, 0x79, 0xbd, 0x18, 0x87, 0x41, 0x32, 0x23, 0xfe, 0xd5, 0x30, 0x35, 0x23, 0xa2, 0x2e, 0x54,
	0xb9, 0x7f, 0x35, 0x12, 0xa9, 0xc9, 0xa3, 0xcb, 0xe5, 0x2e, 0xee, 0xc0, 0x07, 0x36, 0x3a, 0x0e,
	0xaf, 0xf1, 0x37, 0xd0, 0x5b, 0x16, 0x15, 0x73, 0xc6, 0x72, 0x1f, 0xea, 0x92, 0x45, 0x5f, 0x8d,
	0x26, 0xda, 0xe6, 0x06, 0x83, 0x7b, 0xb0, 0xb7, 0xd2, 0x26, 0xe9, 0xee, 0xc1, 0x87, 0x67, 0x54,
	0x58, 0xa1, 0xc8, 0x8c, 0xfb, 0x03, 0xba, 0xab, 0x5b, 0xd2, 0xc0, 0x13, 0x68, 0x69, 0xa1, 0xc2,
	0x94, 0xcd, 0x47, 0xe8, 0xbe, 0x7d, 0x2f, 0x76, 0x67, 0x73, 0x6c, 0x05, 0xcf, 0xc4, 0xd5, 0xb9,
	0x2d, 0xae, 0x5f, 0x2c, 0x07, 0x38, 0xb9, 0x96, 0xfe, 0x65, 0x4a, 0xd7, 0xbc, 0x5e, 0xfc, 0x03,
	0x74, 0x8a, 0x60, 0x13, 0x9d, 0xa5, 0x21, 0x3b, 0xc5, 0xe8, 0x68, 0x23, 0x34, 0x02, 0x1f, 0x00,
	0x3a, 0xa3, 0x62, 0x98, 0xde, 0x7d, 0xd6, 0x33, 0x68, 0x5b, 0x48, 0x79, 0xd0, 0x00, 0x1c, 0x73,
	0x7f, 0xeb, 0xf4, 0x38, 0x22, 0xc5, 0xdf, 0x03, 0xfa, 0x91, 0x45, 0x11, 0x9d, 0x08, 0xf9, 0xef,
	0x91, 0xf1, 0xef, 0x43, 0x25, 0xa6, 0x94, 0x9b, 0x4e, 0x64, 0x77, 0x2a, 0xa0, 0xda, 0xc7, 0x08,
	0xda, 0x56, 0xb7, 0xbc, 0xbc, 0xe7, 0xd0, 0x3d, 0x0d, 0x92, 0xc9, 0xfb, 0x93, 0x76, 0xa1, 0x53,
	0x24, 0x88, 0xc3, 0xeb, 0xcf, 0xef, 0x81, 0xab, 0x1e, 0x15, 0x6a, 0x43, 0xe3, 0xfc, 0xe5, 0x9b,
	0xe3, 0x9f, 0xcf, 0x4f, 0x47, 0xa7, 0xc7, 0xc3, 0xe3, 0xf6, 0xd6, 0xd1, 0x3f, 0x2e, 0x54, 0x5e,
	0xb2, 0x29, 0x45, 0x2f, 0xa0, 0x66, 0x5e, 0x15, 0x7a, 0x60, 0xf3, 0xdb, 0xef, 0xaf, 0xdf, 0xdf,
	0xb0, 0x2b, 0x05, 0x6c, 0xa1, 0x21, 0x34, 0xf2, 0x19, 0x47, 0x8f, 0x0a, 0xb3, 0xae, 0xbe, 0x96,
	0xfe, 0xc3, 0xdb, 0x20, 0x9a, 0xf5, 0x37, 0xd8, 0x2d, 0xa4, 0x1d, 0x7d, 0xba, 0xa9, 0x2b, 0xff,
	0x86, 0xfa, 0xf8, 0x0e, 0x94, 0xa6, 0x1f, 0xab, 0xfb, 0xb7, 0xbf, 0xa4, 0x9f, 0xad, 0xc8, 0x5c,
	0xf7, 0xa8, 0xfa, 0x9f, 0xdc, 0x05, 0x53, 0x27, 0x3c, 0x2d, 0xa1, 0x5f, 0xd5, 0x87, 0x2c, 0x97,
	0x67, 0xb4, 0xa1, 0xd5, 0x8a, 0x6b, 0xff, 0xd1, 0xed, 0x20, 0x3d, 0xff, 0x2f, 0xb0, 0x93, 0xcb,
	0x2f, 0x1a, 0xac, 0xf4, 0x14, 0x1e, 0x41, 0xff, 0xe3, 0x5b, 0x10, 0x37, 0x94, 0xb9, 0x78, 0x16,
	0x29, 0x57, 0x73, 0x5f, 0xa4, 0x5c, 0xc9, 0xf6, 0x96, 0x74, 0xc0, 0x0e, 0x67, 0xd1, 0x81, 0xb5,
	0xd9, 0x2f, 0x3a, 0xb0, 0x26, 0xdf, 0x78, 0x6b, 0x5c, 0x55, 0x5f, 0xf0, 0xaf, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x09, 0x08, 0xc3, 0x03, 0x14, 0x0a, 0x00, 0x00,
}
