// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Version              uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	HashPrevBlock        string   `protobuf:"bytes,4,opt,name=hashPrevBlock,proto3" json:"hashPrevBlock,omitempty"`
	HashMerkleRoot       string   `protobuf:"bytes,5,opt,name=hashMerkleRoot,proto3" json:"hashMerkleRoot,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Bits                 uint32   `protobuf:"varint,8,opt,name=bits,proto3" json:"bits,omitempty"`
	Nonce                uint64   `protobuf:"varint,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,10,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetHashPrevBlock() string {
	if m != nil {
		return m.HashPrevBlock
	}
	return ""
}

func (m *Block) GetHashMerkleRoot() string {
	if m != nil {
		return m.HashMerkleRoot
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetBits() uint32 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Tx struct {
	Version              uint32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string  `protobuf:"bytes,2,rep,name=flags,proto3" json:"flags,omitempty"`
	Inputs               []*Input  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*Output `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{1}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Tx) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Tx) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Tx) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Input struct {
	PreviousOutput       *Outpoint `protobuf:"bytes,1,opt,name=previousOutput,proto3" json:"previousOutput,omitempty"`
	Script               []byte    `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{2}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (dst *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(dst, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetPreviousOutput() *Outpoint {
	if m != nil {
		return m.PreviousOutput
	}
	return nil
}

func (m *Input) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type Outpoint struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outpoint) Reset()         { *m = Outpoint{} }
func (m *Outpoint) String() string { return proto.CompactTextString(m) }
func (*Outpoint) ProtoMessage()    {}
func (*Outpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{3}
}
func (m *Outpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outpoint.Unmarshal(m, b)
}
func (m *Outpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outpoint.Marshal(b, m, deterministic)
}
func (dst *Outpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outpoint.Merge(dst, src)
}
func (m *Outpoint) XXX_Size() int {
	return xxx_messageInfo_Outpoint.Size(m)
}
func (m *Outpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Outpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Outpoint proto.InternalMessageInfo

func (m *Outpoint) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Outpoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Output struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{4}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (dst *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(dst, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Output) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type GetBlockHashAtHeightRequest struct {
	Height               uint32   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashAtHeightRequest) Reset()         { *m = GetBlockHashAtHeightRequest{} }
func (m *GetBlockHashAtHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashAtHeightRequest) ProtoMessage()    {}
func (*GetBlockHashAtHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{5}
}
func (m *GetBlockHashAtHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashAtHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockHashAtHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashAtHeightRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockHashAtHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashAtHeightRequest.Merge(dst, src)
}
func (m *GetBlockHashAtHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashAtHeightRequest.Size(m)
}
func (m *GetBlockHashAtHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashAtHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashAtHeightRequest proto.InternalMessageInfo

func (m *GetBlockHashAtHeightRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetBlockHashAtHeightReply struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHashAtHeightReply) Reset()         { *m = GetBlockHashAtHeightReply{} }
func (m *GetBlockHashAtHeightReply) String() string { return proto.CompactTextString(m) }
func (*GetBlockHashAtHeightReply) ProtoMessage()    {}
func (*GetBlockHashAtHeightReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{6}
}
func (m *GetBlockHashAtHeightReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHashAtHeightReply.Unmarshal(m, b)
}
func (m *GetBlockHashAtHeightReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHashAtHeightReply.Marshal(b, m, deterministic)
}
func (dst *GetBlockHashAtHeightReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHashAtHeightReply.Merge(dst, src)
}
func (m *GetBlockHashAtHeightReply) XXX_Size() int {
	return xxx_messageInfo_GetBlockHashAtHeightReply.Size(m)
}
func (m *GetBlockHashAtHeightReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHashAtHeightReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHashAtHeightReply proto.InternalMessageInfo

func (m *GetBlockHashAtHeightReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockByHashRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashRequest) Reset()         { *m = GetBlockByHashRequest{} }
func (m *GetBlockByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashRequest) ProtoMessage()    {}
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{7}
}
func (m *GetBlockByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashRequest.Merge(dst, src)
}
func (m *GetBlockByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashRequest.Size(m)
}
func (m *GetBlockByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashRequest proto.InternalMessageInfo

func (m *GetBlockByHashRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockByHashReply struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashReply) Reset()         { *m = GetBlockByHashReply{} }
func (m *GetBlockByHashReply) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashReply) ProtoMessage()    {}
func (*GetBlockByHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{8}
}
func (m *GetBlockByHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashReply.Unmarshal(m, b)
}
func (m *GetBlockByHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashReply.Marshal(b, m, deterministic)
}
func (dst *GetBlockByHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashReply.Merge(dst, src)
}
func (m *GetBlockByHashReply) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashReply.Size(m)
}
func (m *GetBlockByHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashReply proto.InternalMessageInfo

func (m *GetBlockByHashReply) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetMainChainHeightRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainChainHeightRequest) Reset()         { *m = GetMainChainHeightRequest{} }
func (m *GetMainChainHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetMainChainHeightRequest) ProtoMessage()    {}
func (*GetMainChainHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{9}
}
func (m *GetMainChainHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainChainHeightRequest.Unmarshal(m, b)
}
func (m *GetMainChainHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainChainHeightRequest.Marshal(b, m, deterministic)
}
func (dst *GetMainChainHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainChainHeightRequest.Merge(dst, src)
}
func (m *GetMainChainHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetMainChainHeightRequest.Size(m)
}
func (m *GetMainChainHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainChainHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainChainHeightRequest proto.InternalMessageInfo

type GetMainChainHeightReply struct {
	Height               uint32   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainChainHeightReply) Reset()         { *m = GetMainChainHeightReply{} }
func (m *GetMainChainHeightReply) String() string { return proto.CompactTextString(m) }
func (*GetMainChainHeightReply) ProtoMessage()    {}
func (*GetMainChainHeightReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{10}
}
func (m *GetMainChainHeightReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainChainHeightReply.Unmarshal(m, b)
}
func (m *GetMainChainHeightReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainChainHeightReply.Marshal(b, m, deterministic)
}
func (dst *GetMainChainHeightReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainChainHeightReply.Merge(dst, src)
}
func (m *GetMainChainHeightReply) XXX_Size() int {
	return xxx_messageInfo_GetMainChainHeightReply.Size(m)
}
func (m *GetMainChainHeightReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainChainHeightReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainChainHeightReply proto.InternalMessageInfo

func (m *GetMainChainHeightReply) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetMainChainRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainChainRequest) Reset()         { *m = GetMainChainRequest{} }
func (m *GetMainChainRequest) String() string { return proto.CompactTextString(m) }
func (*GetMainChainRequest) ProtoMessage()    {}
func (*GetMainChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{11}
}
func (m *GetMainChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainChainRequest.Unmarshal(m, b)
}
func (m *GetMainChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainChainRequest.Marshal(b, m, deterministic)
}
func (dst *GetMainChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainChainRequest.Merge(dst, src)
}
func (m *GetMainChainRequest) XXX_Size() int {
	return xxx_messageInfo_GetMainChainRequest.Size(m)
}
func (m *GetMainChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainChainRequest proto.InternalMessageInfo

type GetMainChainReply struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMainChainReply) Reset()         { *m = GetMainChainReply{} }
func (m *GetMainChainReply) String() string { return proto.CompactTextString(m) }
func (*GetMainChainReply) ProtoMessage()    {}
func (*GetMainChainReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_341d0551a1004ddd, []int{12}
}
func (m *GetMainChainReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMainChainReply.Unmarshal(m, b)
}
func (m *GetMainChainReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMainChainReply.Marshal(b, m, deterministic)
}
func (dst *GetMainChainReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMainChainReply.Merge(dst, src)
}
func (m *GetMainChainReply) XXX_Size() int {
	return xxx_messageInfo_GetMainChainReply.Size(m)
}
func (m *GetMainChainReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMainChainReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMainChainReply proto.InternalMessageInfo

func (m *GetMainChainReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "rpc.Block")
	proto.RegisterType((*Tx)(nil), "rpc.Tx")
	proto.RegisterType((*Input)(nil), "rpc.Input")
	proto.RegisterType((*Outpoint)(nil), "rpc.Outpoint")
	proto.RegisterType((*Output)(nil), "rpc.Output")
	proto.RegisterType((*GetBlockHashAtHeightRequest)(nil), "rpc.GetBlockHashAtHeightRequest")
	proto.RegisterType((*GetBlockHashAtHeightReply)(nil), "rpc.GetBlockHashAtHeightReply")
	proto.RegisterType((*GetBlockByHashRequest)(nil), "rpc.GetBlockByHashRequest")
	proto.RegisterType((*GetBlockByHashReply)(nil), "rpc.GetBlockByHashReply")
	proto.RegisterType((*GetMainChainHeightRequest)(nil), "rpc.GetMainChainHeightRequest")
	proto.RegisterType((*GetMainChainHeightReply)(nil), "rpc.GetMainChainHeightReply")
	proto.RegisterType((*GetMainChainRequest)(nil), "rpc.GetMainChainRequest")
	proto.RegisterType((*GetMainChainReply)(nil), "rpc.GetMainChainReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainClient is the client API for Blockchain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainClient interface {
	GetBlockHashAtHeight(ctx context.Context, in *GetBlockHashAtHeightRequest, opts ...grpc.CallOption) (*GetBlockHashAtHeightReply, error)
	GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashReply, error)
	GetMainChainHeight(ctx context.Context, in *GetMainChainHeightRequest, opts ...grpc.CallOption) (*GetMainChainHeightReply, error)
	GetMainChain(ctx context.Context, in *GetMainChainRequest, opts ...grpc.CallOption) (*GetMainChainReply, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) GetBlockHashAtHeight(ctx context.Context, in *GetBlockHashAtHeightRequest, opts ...grpc.CallOption) (*GetBlockHashAtHeightReply, error) {
	out := new(GetBlockHashAtHeightReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetBlockHashAtHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashReply, error) {
	out := new(GetBlockByHashReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetMainChainHeight(ctx context.Context, in *GetMainChainHeightRequest, opts ...grpc.CallOption) (*GetMainChainHeightReply, error) {
	out := new(GetMainChainHeightReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetMainChainHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetMainChain(ctx context.Context, in *GetMainChainRequest, opts ...grpc.CallOption) (*GetMainChainReply, error) {
	out := new(GetMainChainReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetMainChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServer is the server API for Blockchain service.
type BlockchainServer interface {
	GetBlockHashAtHeight(context.Context, *GetBlockHashAtHeightRequest) (*GetBlockHashAtHeightReply, error)
	GetBlockByHash(context.Context, *GetBlockByHashRequest) (*GetBlockByHashReply, error)
	GetMainChainHeight(context.Context, *GetMainChainHeightRequest) (*GetMainChainHeightReply, error)
	GetMainChain(context.Context, *GetMainChainRequest) (*GetMainChainReply, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_GetBlockHashAtHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHashAtHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockHashAtHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetBlockHashAtHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockHashAtHeight(ctx, req.(*GetBlockHashAtHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlockByHash(ctx, req.(*GetBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetMainChainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMainChainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetMainChainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetMainChainHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetMainChainHeight(ctx, req.(*GetMainChainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetMainChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMainChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetMainChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetMainChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetMainChain(ctx, req.(*GetMainChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockHashAtHeight",
			Handler:    _Blockchain_GetBlockHashAtHeight_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _Blockchain_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetMainChainHeight",
			Handler:    _Blockchain_GetMainChainHeight_Handler,
		},
		{
			MethodName: "GetMainChain",
			Handler:    _Blockchain_GetMainChain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_341d0551a1004ddd) }

var fileDescriptor_rpc_341d0551a1004ddd = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x9c, 0x34, 0x93, 0x26, 0x12, 0x4b, 0x5a, 0xb6, 0x69, 0x85, 0xac, 0x15, 0x3f,
	0x96, 0x90, 0x8a, 0x08, 0x14, 0xce, 0x84, 0x03, 0xe1, 0x50, 0x81, 0x56, 0x11, 0x07, 0x6e, 0x8e,
	0x59, 0xea, 0x55, 0x5d, 0xdb, 0x78, 0x37, 0x51, 0x72, 0xe2, 0x25, 0x78, 0x2c, 0x1e, 0x0a, 0xed,
	0x6c, 0x1c, 0xe2, 0xd4, 0xa9, 0xd4, 0x53, 0x3c, 0xf3, 0xfd, 0x78, 0xe6, 0x9b, 0xc8, 0xd0, 0x29,
	0xf2, 0xe8, 0x3c, 0x2f, 0x32, 0x9d, 0x11, 0xb7, 0xc8, 0x23, 0xf6, 0xa7, 0x01, 0xde, 0x38, 0xc9,
	0xa2, 0x6b, 0x42, 0xa1, 0xbd, 0x10, 0x85, 0x92, 0x59, 0x4a, 0x1d, 0xdf, 0x09, 0x7a, 0xbc, 0x2c,
	0xc9, 0x00, 0xbc, 0x9f, 0x49, 0x78, 0xa5, 0x68, 0xc3, 0x77, 0x83, 0x0e, 0xb7, 0x05, 0x21, 0xd0,
	0x8c, 0x43, 0x15, 0x53, 0xd7, 0x77, 0x82, 0x0e, 0xc7, 0x67, 0xf2, 0x14, 0x7a, 0xe6, 0xf7, 0x6b,
	0x21, 0x16, 0x68, 0x4a, 0x9b, 0x08, 0x56, 0x9b, 0xe4, 0x39, 0xf4, 0x4d, 0xe3, 0x52, 0x14, 0xd7,
	0x89, 0xe0, 0x59, 0xa6, 0xa9, 0x87, 0xb4, 0x9d, 0x2e, 0x39, 0x83, 0x8e, 0x96, 0x37, 0x42, 0xe9,
	0xf0, 0x26, 0xa7, 0x2d, 0xdf, 0x09, 0x5c, 0xfe, 0xbf, 0x41, 0x8e, 0xa1, 0x15, 0x0b, 0x79, 0x15,
	0x6b, 0xda, 0xc6, 0x71, 0xd7, 0x95, 0x99, 0x6b, 0x26, 0xb5, 0xa2, 0x07, 0xd8, 0xc5, 0x67, 0xb3,
	0x41, 0x9a, 0xa5, 0x91, 0xa0, 0x1d, 0xdf, 0x09, 0x9a, 0xdc, 0x16, 0xe4, 0x04, 0x5c, 0xbd, 0x54,
	0x14, 0x7c, 0x37, 0xe8, 0x8e, 0xda, 0xe7, 0x26, 0x99, 0xe9, 0x92, 0x9b, 0x1e, 0xfb, 0x0d, 0x8d,
	0xe9, 0xf2, 0xde, 0x91, 0x30, 0x68, 0xc9, 0x34, 0x9f, 0x6b, 0x45, 0x5d, 0xf4, 0x04, 0xf4, 0xfc,
	0x6c, 0x5a, 0x7c, 0x8d, 0x90, 0x67, 0xd0, 0xce, 0xe6, 0x1a, 0x49, 0x4d, 0x24, 0x75, 0x91, 0xf4,
	0x05, 0x7b, 0xbc, 0xc4, 0xd8, 0x37, 0xf0, 0x50, 0x47, 0x2e, 0xa0, 0x9f, 0x17, 0x62, 0x21, 0xb3,
	0xb9, 0xb2, 0x1c, 0x1c, 0xa5, 0x3b, 0xea, 0x6d, 0x64, 0x99, 0x4c, 0x35, 0xdf, 0x21, 0x99, 0x74,
	0x54, 0x54, 0xc8, 0x5c, 0xd3, 0x86, 0xef, 0x04, 0x87, 0x7c, 0x5d, 0xb1, 0xb7, 0x70, 0x50, 0x6a,
	0x36, 0x17, 0x74, 0xb6, 0x2e, 0x38, 0x00, 0x4f, 0xa6, 0x3f, 0xc4, 0x12, 0x65, 0x3d, 0x6e, 0x0b,
	0xf6, 0x0e, 0x5a, 0x6b, 0xdf, 0x01, 0x78, 0x8b, 0x30, 0x99, 0x0b, 0x14, 0x35, 0xb9, 0x2d, 0xf6,
	0xbe, 0xed, 0x02, 0x4e, 0x3f, 0x09, 0x8d, 0x57, 0x9f, 0x84, 0x2a, 0xfe, 0xa0, 0x27, 0x78, 0x23,
	0x2e, 0x7e, 0xcd, 0x85, 0xd2, 0x5b, 0x27, 0x74, 0xb6, 0x4f, 0xc8, 0x5e, 0xc1, 0x49, 0xbd, 0x2c,
	0x4f, 0x56, 0x75, 0x53, 0xb3, 0x97, 0x70, 0x54, 0x0a, 0xc6, 0x2b, 0x23, 0x29, 0xdf, 0x50, 0x47,
	0x7e, 0x0f, 0x8f, 0x76, 0xc9, 0xc6, 0xd7, 0x07, 0x6f, 0x86, 0xff, 0x59, 0x9b, 0xaf, 0xbd, 0x1d,
	0xb2, 0xb8, 0x05, 0xd8, 0x29, 0x8e, 0x75, 0x19, 0xca, 0xf4, 0x63, 0x1c, 0xca, 0xb4, 0xb2, 0x0b,
	0x7b, 0x0d, 0x8f, 0xeb, 0x40, 0xe3, 0xbc, 0x6f, 0xcd, 0x23, 0x1c, 0x64, 0x23, 0x29, 0x9d, 0x5e,
	0xc0, 0xc3, 0x6a, 0x7b, 0xcf, 0xd6, 0xa3, 0xbf, 0x0d, 0x00, 0x1c, 0x30, 0x32, 0x3c, 0xf2, 0x1d,
	0x06, 0x75, 0xa9, 0x11, 0x1f, 0x37, 0xb9, 0xe3, 0x0e, 0xc3, 0x27, 0x77, 0x30, 0xf2, 0x64, 0xc5,
	0x1e, 0x90, 0x09, 0xf4, 0xab, 0x99, 0x91, 0x61, 0x45, 0x53, 0x49, 0x7d, 0x48, 0x6b, 0x31, 0xeb,
	0x34, 0x05, 0x72, 0x3b, 0x27, 0xb2, 0x99, 0xa0, 0x3e, 0xdd, 0xe1, 0xd9, 0x5e, 0xdc, 0xba, 0x8e,
	0xe1, 0x70, 0x1b, 0x24, 0xf4, 0x16, 0xbf, 0x74, 0x3a, 0xae, 0x41, 0xd0, 0x63, 0xd6, 0xc2, 0xcf,
	0xe2, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x11, 0x4f, 0x87, 0x62, 0x23, 0x05, 0x00, 0x00,
}
