// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Block struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	HashPrevBlock        string   `protobuf:"bytes,4,opt,name=hashPrevBlock,proto3" json:"hashPrevBlock,omitempty"`
	HashMerkleRoot       string   `protobuf:"bytes,5,opt,name=hashMerkleRoot,proto3" json:"hashMerkleRoot,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Bits                 uint32   `protobuf:"varint,8,opt,name=bits,proto3" json:"bits,omitempty"`
	Nonce                uint64   `protobuf:"varint,9,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,10,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{1}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Block) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Block) GetHashPrevBlock() string {
	if m != nil {
		return m.HashPrevBlock
	}
	return ""
}

func (m *Block) GetHashMerkleRoot() string {
	if m != nil {
		return m.HashMerkleRoot
	}
	return ""
}

func (m *Block) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Block) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetBits() uint32 {
	if m != nil {
		return m.Bits
	}
	return 0
}

func (m *Block) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Block) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Tx struct {
	Hash                 string    `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Version              uint32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Flags                []string  `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	Inputs               []*Input  `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*Output `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{2}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tx) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Tx) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Tx) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Tx) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type Input struct {
	PreviousOutput       *Outpoint `protobuf:"bytes,1,opt,name=previousOutput,proto3" json:"previousOutput,omitempty"`
	Script               []byte    `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{3}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (dst *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(dst, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetPreviousOutput() *Outpoint {
	if m != nil {
		return m.PreviousOutput
	}
	return nil
}

func (m *Input) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type Outpoint struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outpoint) Reset()         { *m = Outpoint{} }
func (m *Outpoint) String() string { return proto.CompactTextString(m) }
func (*Outpoint) ProtoMessage()    {}
func (*Outpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{4}
}
func (m *Outpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outpoint.Unmarshal(m, b)
}
func (m *Outpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outpoint.Marshal(b, m, deterministic)
}
func (dst *Outpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outpoint.Merge(dst, src)
}
func (m *Outpoint) XXX_Size() int {
	return xxx_messageInfo_Outpoint.Size(m)
}
func (m *Outpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Outpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Outpoint proto.InternalMessageInfo

func (m *Outpoint) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Outpoint) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Output struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{5}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (dst *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(dst, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Output) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type GetBlockRequest struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockRequest) Reset()         { *m = GetBlockRequest{} }
func (m *GetBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockRequest) ProtoMessage()    {}
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{6}
}
func (m *GetBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockRequest.Unmarshal(m, b)
}
func (m *GetBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockRequest.Merge(dst, src)
}
func (m *GetBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockRequest.Size(m)
}
func (m *GetBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockRequest proto.InternalMessageInfo

func (m *GetBlockRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetBlockReply struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockReply) Reset()         { *m = GetBlockReply{} }
func (m *GetBlockReply) String() string { return proto.CompactTextString(m) }
func (*GetBlockReply) ProtoMessage()    {}
func (*GetBlockReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{7}
}
func (m *GetBlockReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockReply.Unmarshal(m, b)
}
func (m *GetBlockReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockReply.Marshal(b, m, deterministic)
}
func (dst *GetBlockReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockReply.Merge(dst, src)
}
func (m *GetBlockReply) XXX_Size() int {
	return xxx_messageInfo_GetBlockReply.Size(m)
}
func (m *GetBlockReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockReply proto.InternalMessageInfo

func (m *GetBlockReply) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetBestBlockHashRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBestBlockHashRequest) Reset()         { *m = GetBestBlockHashRequest{} }
func (m *GetBestBlockHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBestBlockHashRequest) ProtoMessage()    {}
func (*GetBestBlockHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{8}
}
func (m *GetBestBlockHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBestBlockHashRequest.Unmarshal(m, b)
}
func (m *GetBestBlockHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBestBlockHashRequest.Marshal(b, m, deterministic)
}
func (dst *GetBestBlockHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestBlockHashRequest.Merge(dst, src)
}
func (m *GetBestBlockHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBestBlockHashRequest.Size(m)
}
func (m *GetBestBlockHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestBlockHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestBlockHashRequest proto.InternalMessageInfo

type GetBestBlockHashReply struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBestBlockHashReply) Reset()         { *m = GetBestBlockHashReply{} }
func (m *GetBestBlockHashReply) String() string { return proto.CompactTextString(m) }
func (*GetBestBlockHashReply) ProtoMessage()    {}
func (*GetBestBlockHashReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{9}
}
func (m *GetBestBlockHashReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBestBlockHashReply.Unmarshal(m, b)
}
func (m *GetBestBlockHashReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBestBlockHashReply.Marshal(b, m, deterministic)
}
func (dst *GetBestBlockHashReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBestBlockHashReply.Merge(dst, src)
}
func (m *GetBestBlockHashReply) XXX_Size() int {
	return xxx_messageInfo_GetBestBlockHashReply.Size(m)
}
func (m *GetBestBlockHashReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBestBlockHashReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBestBlockHashReply proto.InternalMessageInfo

func (m *GetBestBlockHashReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type PublishTxRequest struct {
	Tx                   []byte   `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishTxRequest) Reset()         { *m = PublishTxRequest{} }
func (m *PublishTxRequest) String() string { return proto.CompactTextString(m) }
func (*PublishTxRequest) ProtoMessage()    {}
func (*PublishTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{10}
}
func (m *PublishTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishTxRequest.Unmarshal(m, b)
}
func (m *PublishTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishTxRequest.Marshal(b, m, deterministic)
}
func (dst *PublishTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishTxRequest.Merge(dst, src)
}
func (m *PublishTxRequest) XXX_Size() int {
	return xxx_messageInfo_PublishTxRequest.Size(m)
}
func (m *PublishTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishTxRequest proto.InternalMessageInfo

func (m *PublishTxRequest) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type PublishTxReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishTxReply) Reset()         { *m = PublishTxReply{} }
func (m *PublishTxReply) String() string { return proto.CompactTextString(m) }
func (*PublishTxReply) ProtoMessage()    {}
func (*PublishTxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_39aa7423ac78f165, []int{11}
}
func (m *PublishTxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishTxReply.Unmarshal(m, b)
}
func (m *PublishTxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishTxReply.Marshal(b, m, deterministic)
}
func (dst *PublishTxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishTxReply.Merge(dst, src)
}
func (m *PublishTxReply) XXX_Size() int {
	return xxx_messageInfo_PublishTxReply.Size(m)
}
func (m *PublishTxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishTxReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishTxReply proto.InternalMessageInfo

func (m *PublishTxReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *PublishTxReply) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "rpc.Error")
	proto.RegisterType((*Block)(nil), "rpc.Block")
	proto.RegisterType((*Tx)(nil), "rpc.Tx")
	proto.RegisterType((*Input)(nil), "rpc.Input")
	proto.RegisterType((*Outpoint)(nil), "rpc.Outpoint")
	proto.RegisterType((*Output)(nil), "rpc.Output")
	proto.RegisterType((*GetBlockRequest)(nil), "rpc.GetBlockRequest")
	proto.RegisterType((*GetBlockReply)(nil), "rpc.GetBlockReply")
	proto.RegisterType((*GetBestBlockHashRequest)(nil), "rpc.GetBestBlockHashRequest")
	proto.RegisterType((*GetBestBlockHashReply)(nil), "rpc.GetBestBlockHashReply")
	proto.RegisterType((*PublishTxRequest)(nil), "rpc.PublishTxRequest")
	proto.RegisterType((*PublishTxReply)(nil), "rpc.PublishTxReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainClient is the client API for Blockchain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainClient interface {
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockReply, error)
	GetBestBlockHash(ctx context.Context, in *GetBestBlockHashRequest, opts ...grpc.CallOption) (*GetBestBlockHashReply, error)
}

type blockchainClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainClient(cc *grpc.ClientConn) BlockchainClient {
	return &blockchainClient{cc}
}

func (c *blockchainClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockReply, error) {
	out := new(GetBlockReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainClient) GetBestBlockHash(ctx context.Context, in *GetBestBlockHashRequest, opts ...grpc.CallOption) (*GetBestBlockHashReply, error) {
	out := new(GetBestBlockHashReply)
	err := c.cc.Invoke(ctx, "/rpc.Blockchain/GetBestBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainServer is the server API for Blockchain service.
type BlockchainServer interface {
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockReply, error)
	GetBestBlockHash(context.Context, *GetBestBlockHashRequest) (*GetBestBlockHashReply, error)
}

func RegisterBlockchainServer(s *grpc.Server, srv BlockchainServer) {
	s.RegisterService(&_Blockchain_serviceDesc, srv)
}

func _Blockchain_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blockchain_GetBestBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBestBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainServer).GetBestBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Blockchain/GetBestBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainServer).GetBestBlockHash(ctx, req.(*GetBestBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Blockchain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Blockchain",
	HandlerType: (*BlockchainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlock",
			Handler:    _Blockchain_GetBlock_Handler,
		},
		{
			MethodName: "GetBestBlockHash",
			Handler:    _Blockchain_GetBestBlockHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// TxsClient is the client API for Txs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TxsClient interface {
	PublishTx(ctx context.Context, in *PublishTxRequest, opts ...grpc.CallOption) (*PublishTxReply, error)
}

type txsClient struct {
	cc *grpc.ClientConn
}

func NewTxsClient(cc *grpc.ClientConn) TxsClient {
	return &txsClient{cc}
}

func (c *txsClient) PublishTx(ctx context.Context, in *PublishTxRequest, opts ...grpc.CallOption) (*PublishTxReply, error) {
	out := new(PublishTxReply)
	err := c.cc.Invoke(ctx, "/rpc.Txs/PublishTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxsServer is the server API for Txs service.
type TxsServer interface {
	PublishTx(context.Context, *PublishTxRequest) (*PublishTxReply, error)
}

func RegisterTxsServer(s *grpc.Server, srv TxsServer) {
	s.RegisterService(&_Txs_serviceDesc, srv)
}

func _Txs_PublishTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxsServer).PublishTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Txs/PublishTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxsServer).PublishTx(ctx, req.(*PublishTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Txs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Txs",
	HandlerType: (*TxsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTx",
			Handler:    _Txs_PublishTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_39aa7423ac78f165) }

var fileDescriptor_rpc_39aa7423ac78f165 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x49, 0xd3, 0x2e, 0xb7, 0x6b, 0x99, 0x4c, 0x07, 0x5e, 0xd9, 0x43, 0x64, 0x31, 0x54,
	0x09, 0x69, 0x12, 0x05, 0x26, 0xf1, 0x86, 0x90, 0xf8, 0x7a, 0x00, 0x26, 0xab, 0xe2, 0x3d, 0xcd,
	0xcc, 0x12, 0x2d, 0x8b, 0x83, 0xed, 0x54, 0xd9, 0xef, 0x60, 0x3f, 0x18, 0xf9, 0x3a, 0x6d, 0x59,
	0xe8, 0xde, 0x78, 0xf3, 0x3d, 0xe7, 0xdc, 0x8f, 0x73, 0x75, 0x13, 0x88, 0x54, 0x95, 0x9e, 0x56,
	0x4a, 0x1a, 0x49, 0x02, 0x55, 0xa5, 0xec, 0x29, 0x84, 0x1f, 0x94, 0x92, 0x8a, 0x10, 0xe8, 0xa5,
	0xf2, 0x42, 0x50, 0x2f, 0xf6, 0x66, 0x23, 0x8e, 0x6f, 0x76, 0xeb, 0x43, 0xf8, 0xbe, 0x90, 0xe9,
	0x95, 0x65, 0xb3, 0x44, 0x67, 0xc8, 0x46, 0x1c, 0xdf, 0x84, 0xc2, 0x60, 0x25, 0x94, 0xce, 0x65,
	0x49, 0x7d, 0x4c, 0x5a, 0x87, 0x64, 0x02, 0xe1, 0xcf, 0x22, 0xb9, 0xd4, 0x34, 0x88, 0x83, 0x59,
	0xc4, 0x5d, 0x40, 0x9e, 0xc1, 0xc8, 0xe6, 0x9d, 0x2b, 0xb1, 0xc2, 0xa2, 0xb4, 0x87, 0xc5, 0xee,
	0x82, 0xe4, 0x39, 0x8c, 0x2d, 0xf0, 0x55, 0xa8, 0xab, 0x42, 0x70, 0x29, 0x0d, 0x0d, 0x51, 0xd6,
	0x41, 0xc9, 0x31, 0x44, 0x26, 0xbf, 0x16, 0xda, 0x24, 0xd7, 0x15, 0xed, 0xc7, 0xde, 0x2c, 0xe0,
	0x5b, 0x80, 0x3c, 0x86, 0x7e, 0x26, 0xf2, 0xcb, 0xcc, 0xd0, 0x01, 0x8e, 0xd6, 0x46, 0xd6, 0xc7,
	0x32, 0x37, 0x9a, 0xee, 0x39, 0x97, 0xf6, 0x6d, 0xa7, 0x2d, 0x65, 0x99, 0x0a, 0x1a, 0xc5, 0xde,
	0xac, 0xc7, 0x5d, 0x40, 0x8e, 0x20, 0x30, 0x8d, 0xa6, 0x10, 0x07, 0xb3, 0xe1, 0x7c, 0x70, 0x6a,
	0xd7, 0xb6, 0x68, 0xb8, 0xc5, 0xd8, 0x6f, 0x0f, 0xfc, 0x45, 0xf3, 0x5f, 0x76, 0xc2, 0xa0, 0x9f,
	0x97, 0x55, 0x6d, 0x34, 0xed, 0x61, 0x23, 0xc0, 0x46, 0x5f, 0x2c, 0xc4, 0x5b, 0x86, 0x9c, 0xc0,
	0x40, 0xd6, 0x06, 0x45, 0x21, 0x8a, 0x86, 0x28, 0xfa, 0x8e, 0x18, 0x5f, 0x73, 0xec, 0x07, 0x84,
	0x98, 0x47, 0xde, 0xc0, 0xb8, 0x52, 0x62, 0x95, 0xcb, 0x5a, 0x3b, 0x0d, 0x4e, 0x38, 0x9c, 0x8f,
	0x36, 0x69, 0x32, 0x2f, 0x0d, 0xef, 0x88, 0xec, 0xca, 0x74, 0xaa, 0xf2, 0xca, 0xe0, 0xe4, 0xfb,
	0xbc, 0x8d, 0xd8, 0x6b, 0xd8, 0x5b, 0xe7, 0xec, 0xb4, 0x3c, 0x81, 0x30, 0x2f, 0x2f, 0x44, 0xd3,
	0x1a, 0x76, 0x01, 0x3b, 0x83, 0x7e, 0x5b, 0x77, 0x02, 0xe1, 0x2a, 0x29, 0x6a, 0x77, 0x59, 0x3d,
	0xee, 0x82, 0x7b, 0xbb, 0x9d, 0xc0, 0xc3, 0x4f, 0xc2, 0xe0, 0x29, 0x70, 0xf1, 0xab, 0x16, 0x7a,
	0x67, 0x53, 0xf6, 0x12, 0x46, 0x5b, 0x59, 0x55, 0xdc, 0x90, 0x18, 0xc2, 0x25, 0x1e, 0x95, 0xf3,
	0xea, 0xf6, 0xe8, 0x78, 0x47, 0xb0, 0x23, 0x78, 0x62, 0x53, 0x84, 0x76, 0x69, 0x9f, 0x13, 0x9d,
	0xb5, 0x1d, 0xd8, 0x0b, 0x38, 0xfc, 0x97, 0xb2, 0x55, 0x77, 0xb5, 0x66, 0x70, 0x70, 0x5e, 0x2f,
	0x8b, 0x5c, 0x67, 0x8b, 0x66, 0x3d, 0xe2, 0x18, 0x7c, 0xd3, 0xa0, 0x6a, 0x9f, 0xfb, 0xa6, 0x61,
	0x1f, 0x61, 0xfc, 0x97, 0xa6, 0x9d, 0x4f, 0xd8, 0xef, 0xec, 0xce, 0x7c, 0xf8, 0xe5, 0x71, 0x47,
	0x6c, 0x7a, 0xf9, 0xdb, 0x5e, 0xf3, 0x5b, 0x0f, 0x00, 0x47, 0x4a, 0xb3, 0x24, 0x2f, 0xc9, 0x19,
	0xec, 0xad, 0x5d, 0x93, 0x09, 0x56, 0xe8, 0xec, 0x6a, 0x4a, 0x3a, 0x68, 0x55, 0xdc, 0xb0, 0x07,
	0xe4, 0x1b, 0x1c, 0x74, 0xfd, 0x91, 0xe3, 0x8d, 0x72, 0xc7, 0x46, 0xa6, 0xd3, 0x7b, 0x58, 0xac,
	0x37, 0x7f, 0x07, 0xc1, 0xa2, 0xd1, 0xe4, 0x2d, 0x44, 0x1b, 0x97, 0xe4, 0x10, 0x33, 0xba, 0x9b,
	0x99, 0x3e, 0xea, 0xc2, 0x58, 0x61, 0xd9, 0xc7, 0x5f, 0xd0, 0xab, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xbd, 0xbd, 0xb0, 0x74, 0x8f, 0x04, 0x00, 0x00,
}
